### ISSUE TITLE
assertDisplayedAtPosition doesn't assert displayed list view

### ISSUE THREAD

**Issue by headsvk** [AdevintaSpain/Barista#283]
Hi,
I found a problem with `BaristaListAssertions.assertDisplayedAtPosition(...)`.
When multiple list ids match (like in a ViewPager), it scrolls the displayed list but then it asserts on the first list that matches the id.

I believe the problem is in internal `matchRecyclerView` and `matchListView` functions.
https://github.com/SchibstedSpain/Barista/blob/aed99b678889a16bbfdf08657740122698691d54/library/src/main/java/com/schibsted/spain/barista/assertion/BaristaListAssertions.kt#L108
They both use simple `view.rootView.findViewById` which returns the first match.

**Comment by Sloy** [comment]
Hi @headsvk. I'm very sorry for not getting back to you sooner. 

I'm not personally familiar with the code in `BaristaListAssertions`, but I don't think that `assertDisplayedAtPosition()` supports multiple lists with the same id as other Barista functions do.

Would you be able to create a tests reproducing the issue so we could try to find a solution?

**Comment by ridcully99** [comment]
I have the exactly same issue as @headsvk does.

**Comment by ridcully99** [comment]
And here is our horrible fix for it :-)
We had to backport a part of barista 3.0.0 anyways (because we need to support Android 16), so I did this in the atPositionOnList() method:

```
//View listView = view.getRootView().findViewById(listId);
View listView = findDisplayedViewById(view.getRootView(), listId);

```
And here is our findDisplayedViewById() method:

```
    private static View findDisplayedViewById(View view, @IdRes int id) {
        if (id == NO_ID || view.getVisibility() != View.VISIBLE || !view.getGlobalVisibleRect(new Rect())) {
            return null;
        }
        if (view.getId() == id) {
            return view;
        } else if (view instanceof ViewGroup) {
            ViewGroup group = (ViewGroup)view;
            final int len = group.getChildCount();
            for (int i = 0; i < len; i++) {
                View result = findDisplayedViewById(group.getChildAt(i), id);
                if (result != null) {
                    return result;
                }
            }
        }
        return null;
    }
```
