### ISSUE TITLE
assertDisplayed with resource and string not check visibility

### ISSUE THREAD

**Issue by josinaldobarbosa** [AdevintaSpain/Barista#294]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

2.10.0
  
**Describe the Bug:**

assertDisplayed(@IdRes viewId: Int, text: String) not verify if the view is visible

**Comment by josinaldobarbosa** [comment]
I do not know if it is the same case, but there are others with the same behavior, for example: assertHasBackground

**Comment by rocboronat** [comment]
Hello @josinaldobarbosa! I don't understand the issue. What is what you expect that is not happening? Thank you! :·)

**Comment by josinaldobarbosa** [comment]
@rocboronat my bad, if the view of the parameter has visibility gone/invisibility, the test should fail

**Comment by josinaldobarbosa** [comment]
@Sloy Has this been fixed?

**Comment by Sloy** [comment]
Woops sorry @josinaldobarbosa, I misread you.
Would you be able to submit a test case reproducing the issue? So we're sure we understand what's the error you're describing and fix it.

**Comment by josinaldobarbosa** [comment]
Sorry for the delay, but to test it is simply to put the view with invisible that the test will pass.

```
<TextView
        android:text="Hello World!"
        android:id="@+id/my_textview"
        android:visibility="gone"/>
```

`assertDisplayed(R.id.my_textview, "Hello World!")`

**Comment by nickmi11er** [comment]
@Sloy @rocboronat Is there any plans to fix this issue?

**Comment by rocboronat** [comment]
@nickmi11er I've just seen your PR! Thanks for it! Let's move on there 😄

**Comment by Sloy** [comment]
Fixed by https://github.com/AdevintaSpain/Barista/pull/316

Thanks a lot for the report! And sorry for not responding sooner 🙏
