### ISSUE TITLE
Assert color for id in RecyclerView.

### ISSUE THREAD

**Issue by rozautd** [AdevintaSpain/Barista#337]
I have a problem with assert Color for id in recycler view.  I have a button where is indicator, and this indicator change own Color if is check. 
I need the function to which pass:
- Id recycler view 
- postion 
- id button (indicator in my example) 
- and color id.

**Comment by rocboronat** [comment]
Hello! This is a very tailored feature. It would be awesome if you could open a PR that implements it.

**Comment by alorma** [comment]
Hi @rozautd 

We provide the method `assertCustomAssertionAtPosition` to do custom requests on a list / recycler view position, so you can directly create it.
