### ISSUE TITLE
minSDK require at least 19.

### ISSUE THREAD

**Issue by haitrvnvn** [AdevintaSpain/Barista#338]
Version: 3.2.0 minSdk at least 19 require
`ERROR: Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 19 declared in library [com.schibsted.spain:barista:3.2.0] /Users/haitrvn/.gradle/caches/transforms-2/files-2.1/772aaf61cd604787cce5398489c0064e/barista-3.2.0/AndroidManifest.xml as the library might be using APIs not available in 14
	Suggestion: use a compatible library with a minSdk of at most 14,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.schibsted.spain.barista" to force usage (may lead to runtime failures)`
If i change version in build.gradle to 2.9.0 it no require at all.

**Comment by rocboronat** [comment]
Hello!

Android 4.4 was released on 2013. That's big time! As you said, if you need to use that older version of Android, use an old version of Barista. But we can't keep Barista great and only use old API's at the same time.

Or that's what we thought at some moment! 😄 Please, if you find a way of offering the same API Barista offers and work on that old Android version, please open a PR.

Thanks a lot for your feedback! 😊
