### ISSUE TITLE
Espresso Intents

### ISSUE THREAD

**Issue by theapache64** [AdevintaSpain/Barista#342]
**Description what you'd like to happen:**
```
assertIntended(
    clickListItem(R.id.rv_users, 0), // mandatory
    UserDetailActivity::class.java.name, // mandatory
    intentData // optional
)
```

**Example espresso code if available**

```kotlin
Intents.init()
// ... clickListItem(R.id.rv_users, 0)
intended(
    allOf(
        hasComponent(UserDetailActivity::class.java.name)
    )
)
Intents.release()
```

**Comment by Sloy** [comment]
Hi @theapache64! Thanks for the suggestion. We're not currently considering adding any special DSL for intents, except for very weird and complex cases like `mockAndroidCamera()`.

**Comment by theapache64** [comment]
The suggested function is a normal function. :grimacing:

**Comment by Sloy** [comment]
Yes, sorry. By "DSL" I meant "Barista methods" 😅

**Comment by theapache64** [comment]
:rofl: Alright. Anyways, good work guys. I've been searching for your email to thank in person. 
I've recently replaced all espresso test cases with barista methods in one of my pet projects. :)

**Comment by rocboronat** [comment]
I'll print and frame your comment and have it near my screen. When something bad happened, I'll read it and be happy again 😄

**Comment by theapache64** [comment]
Haha. I would also say this library is so underrated. If i had access to `developer.android.com` docs, I'd have replaced all espresso samples with Barista. :sunglasses:

**Comment by Sloy** [comment]
😂Thank you so much @theapache64, that's very kind of you to say. 😊
I'm very happy that Barista is helping you.

**Comment by lachudra87** [comment]
Place for "Thank You notes" would be awesome ;) With Barista I even convinced all the people from my project that writing android UI test could be fun :)

**Comment by rocboronat** [comment]
Hahahaha! What do you think about opening an issue and linking it from the readme? 😄  @Sloy @alorma @EsteveAguilera @alorma @lachudra87 @theapache64

**Comment by theapache64** [comment]
Sure! Who's gonna do it?

**Comment by rocboronat** [comment]
Let's wait for @Sloy 😅 Maybe he has a better idea 😄

**Comment by Sloy** [comment]
Sounds cool! And thank you for the proposal, I really appreciate the gesture.
Maybe also hit `@AdevintaEng` on Twitter so they realize the community finds this library useful :)

**Comment by theapache64** [comment]
I am gonna close this issue for now. See you there in #344 :wink:

**Comment by rocboronat** [comment]
See you there! 😂
