### ISSUE TITLE
WaitForView except sleep

### ISSUE THREAD

**Issue by Murtaza-arif** [AdevintaSpain/Barista#355]
Explicitly using sleep is not bad practice instead of that we could use a dynamic value like watcher or something it would be great.
We could something like this
https://github.com/AzimoLabs/ConditionWatcher

**Comment by Sloy** [comment]
I'm sorry @Murtaza-arif, I have to disagree. Generally using sleep to wait for background things is not a good way to deal with asynchronous operations. They make tests slower, less reliable, and hide or postpone issues. 
We've used them in the past and paid the consequences.

Idling Resources should always be the preferred way to go. For some edge cases when Idlining Resources are not viable or would be too hard to implement, you can use additional libraries like the ConditionWatcher you mentioned, or even https://github.com/americanexpress/busybee which simplifies working with IdlingResources.

And if none of this works for you, you can easily implement a custom `waitForView` function in your project using Barista's `sleep` and `assertDisplayed` functions. But I wouldn't be comfortable adding that function to Barista as a standard way of doing tests. I hope you understand.

**Comment by rocboronat** [comment]
I'm closing this issue because it doesn't have any activity, and it may add noise to our almost empty (haha!) list of issues. Feel free to reopen it, @Murtaza-arif, if you don't agree with @Sloy's answer 😃
