### ISSUE TITLE
Pass the tests in both Day and Night mode

### ISSUE THREAD

**Issue by rocboronat** [AdevintaSpain/Barista#358]
Sometimes, when you develop the Night Mode you put there some `if` clauses.

It would be great that Barista passes the tests in both Day and Night mode, magically, just to try all the paths the code has.

**Comment by alorma** [comment]
You mean adding a `Rule` into our `BaristaRule` to run all tests twice? Or make it optional?

**Comment by alorma** [comment]
Also, we can create a rule to pass tests in both modes, day and night, but as an independent rule

**Comment by rocboronat** [comment]
Ammmm I think that by default it should try both if the device offers the dark mode. But it should be easy to disable, in case the developer thinks it's not needed, either because the app code doesn't change between day and night or because it slows the tests too much.

**Comment by alorma** [comment]
Done in #359

**Comment by Sloy** [comment]
I would not enable it by default because it can break things. For example, if the user depends on Orchestrator to clear the app data between tests. You need to know what you're doing.

**Comment by rocboronat** [comment]
Let's go with just having the Night Mode Rule. I will add it to my own project Rule chain so that will do the job.

Thanks @alorma for the PR and @Sloy for the comments! 👍
