### ISSUE TITLE
[Java] ListView - i think it does not works on ListView with objects

### ISSUE THREAD

**Issue by panarik** [AdevintaSpain/Barista#364]
Hello!

May You see my experience with Barista?

When I start this code:
`assertDisplayedAtPosition(R.id.main_drawerGridView, 0, "Contact");`

Test go to fail with error:
`com.schibsted.spain.barista.internal.failurehandler.BaristaException: Could not perform action (scroll to) on ListView (is displayed on the screen to the user and is assignable from class: class android.widget.AbsListView and with id is <com.github.panarik.smartlauncher:id/main_drawerGridView>)`

Test most be match first position on GridView for my LauncherApp. GreedView dase on ListView with objects AppsData (name, logo)

Environment:
This commit - https://github.com/panarik/SmartLauncher/commit/c6419880616124353eeaf4e0968c7b3b9da1552b
Java
Compile SDK - 29

Thank You!

**Comment by Sloy** [comment]
Hello @panarik!
Are you able to reproduce this issue using the sample tests in Barista?

**Comment by rocboronat** [comment]
I would close this issue... it's stale and we tested the ListView interactions a lot.
