### ISSUE TITLE
Failed integration

### ISSUE THREAD

**Issue by garispe** [AdevintaSpain/Barista#376]
**Library Version:**

3.7.0
  
**Describe the Bug:**

I followed the instructions to integrate Barista. I put this lines in my build.gradle

```groovy
androidTestImplementation('com.schibsted.spain:barista:3.7.0') {
  exclude group: 'org.jetbrains.kotlin'
}
```

But when I try to use it, Android Studio don't recognize the library.

What is my error?

I'm using Android Studio **4.1** and com.android.tools.build:gradle **4.0.1**

**Comment by garispe** [comment]
The problem seems to have to do with offline mode. Sorry for the noise. Barista is great! Thanks!

**Comment by Sloy** [comment]
I'm glad you could found the cause so quickly! :)
