### ISSUE TITLE
Kaspresso union

### ISSUE THREAD

**Issue by matzuk** [AdevintaSpain/Barista#377]
Hi guys!

Let's join our efforts to make Android UI Testing easier! I am an author of the [Kaspresso library](https://github.com/KasperskyLab/Kaspresso).
What do you think about an alliance of our libraries?

**Comment by Sloy** [comment]
Hello @matzuk!
What do you suggest? Do you have something in mind already?

**Comment by rocboronat** [comment]
We could close this issue. Smells stale.
