### ISSUE TITLE
JCenter is shutting down, are there plans to migrate?

### ISSUE THREAD

**Issue by sapuglha** [AdevintaSpain/Barista#382]
I removed `JCenter()` from my project and only left it with `google()` and `mavenCentral()`; Barista was not found.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Are there plans to make it available elsewhere?

**Comment by Sloy** [comment]
Hi @sapuglha! Yes, we're working our projects to an alternative place soon.
In the meantime, Barista is still available in JCenter, and current versions will be available for a year.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by marcoRS** [comment]
Would be great to get this migrated to `mavenCentral()`. This is the only library in our project that is still on `jcenter()`.

**Comment by rocboronat** [comment]
Hi @marcoRS. Don't worry, we will :·)

**Comment by Sloy** [comment]
Sorry it's taking so long! It's taking more bureaucracy than we expected.We are still on it internally. We will migrate as soon as possible. 

But don't panic! JCenter is going to be kept in read only mode indefinitely, so your builds won't break.

**Comment by hanifalfaqih** [comment]
Look's great, i'll be waiting for this migrate to `mavenCentral()`

**Comment by Faltenreich** [comment]
Just to be sure: The migration taking longer is the reason that the current version 3.10.0 has not been published yet, isn't it? Anyways thank you very much for your effort and this awesome library. Keep on rockin'!

**Comment by alorma** [comment]
Yes @Faltenreich .

We couldn't release 3.10.0 because of this. We are working on updating our release process.. but you know, enterprise things take long

**Comment by dferrandezsanchez** [comment]
A work around it could be using jitpack.io:

https://jitpack.io/p/SchibstedSpain/Barista

Hope to be helpfull

**Comment by Sloy** [comment]
Hello all!
I'm pleased to announce that Barista is finally published on Maven Central 🎉  [Version 4.0.0 is now available](https://search.maven.org/artifact/com.adevinta.android/barista/4.0.0/jar).

Some important changes:
- The maven coordinates changed from `com.schibsted.spain:barista` to `com.adevinta.android:barista`. Update your `build.gradle` file.
- The java packages changed from `com.schibsted.spain.barista` to `com.adevinta.android.barista`. A quick "find & replace" should help you with the migration.


Sorry for the delay. It was a long and unpleasant bureaucratic process involving many people in the company.
Thank you @alorma and @ggm for all your efforts! ❤️
