### ISSUE TITLE
Is Barista Browserstack compatible?

### ISSUE THREAD

**Issue by egek92** [AdevintaSpain/Barista#393]
https://www.browserstack.com

**Comment by Sloy** [comment]
I haven't tried it, but the web says it's compatible with Espresso so it should be compatible with Barista too.

**Comment by egek92** [comment]
the answer is yes

**Comment by rocboronat** [comment]
The answer is thank you Sloy for answering so quickly on Monday morning.

**Comment by egek92** [comment]
I wanted to be clear in case of uncertainty when someone checks this issue, but ok ahahah
