### ISSUE TITLE
writeTo(R.id.edit_text, "String with Spaces") does not respect the EditText filter, to disallow specfic characters

### ISSUE THREAD

**Issue by ozmium** [AdevintaSpain/Barista#395]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

3.9.0

```javascript
dependencies {
    ...
    androidTestImplementation('com.schibsted.spain:barista:3.9.0') {
        exclude group: 'org.jetbrains.kotlin' // Only if you already use Kotlin in your project
    }
}
```

**Describe the Bug:**

Layout has:

```xml
<com.google.android.material.textfield.TextInputEditText
    android:id="@+id/edit_text"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:focusableInTouchMode="true"
    android:hint="Type some text with spaces"
    android:digits="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890"
    android:inputType="textFilter"
    android:singleLine="true"
    android:imeOptions="actionNext" />
```

Notice the `android:digits` and `android:inputType` which create a filter to allow or disallow certain characters. Spaces are disallowed. See: https://stackoverflow.com/questions/33993041/android-disable-space-only-for-edittext

`writeTo(R.id.edit_text, "String with Spaces")` adds spaces to the EditText which has disallowed spaces.

Unit test has:

```kotlin
// Barista methods:
writeTo(R.id.edit_text, "String With Spaces")
assertDisplayed(R.id.edit_text, "StringWithSpaces") // assertion fails

// Espresso methods:
onView(withId(R.id.edit_text)).perform(typeText("String With Spaces"))
onView(withId(R.id.edit_text)).check(matches(withText("StringWithSpaces"))) // assertion passes
```

**Steps to reproduce the bug:**
1. Create an `EditText` or `TextInputEditText` which uses a filter and restricted digits, like the example above. See https://stackoverflow.com/questions/33993041/android-disable-space-only-for-edittext
2. Write a Barista test to type characters into this EditText. The characters should include some of the disallowed characters, like spaces.
3. Assert with Barista that the EditText does not contain the disallowed characters

**Expected Behavior:**

Barista should not insert the disallowed characters, because a user would not be able to do this with the on-screen keyboard. The Barista assertion for the correct string should pass. Barista's `writeTo()` should behave like Espresso's `typeText()`.

**Actual Behavior:**

Barista inserts the disallowed characters into the EditText. The Barista assertion for the correct string fails.

**Comment by Sloy** [comment]
Hi @ozmium! Thanks for the report :) 
The `writeTo` function is based on `EditText.setText(string)`. If `setText` allows to ignore the inputType, so does Barista unfortunately. 

I'm not sure that there's an easy fix for this. Can you think of anything?

**Comment by ozmium** [comment]
I had a brief look through the source code of Barista. I may be wrong, but I believe the problem is caused by [Barista's writeTo()](https://github.com/AdevintaSpain/Barista/blob/1c2f532237da8416c749dceaee4f4a43f23fcdc5/library/src/main/java/com/schibsted/spain/barista/interaction/BaristaEditTextInteractions.kt#L23) using `Espresso.replaceText()` instead of the normal `Espresso.typeText()`.

### Suggestions:

**1. Perhaps make `writeTo()` detect if a `textFilter` or `digits` or `maxLength `is being used, and if so, use `typeText()` instead of `replaceText()`.**

Example pseudo code:

```java
fun writeTo(@IdRes editTextId: Int, text: String) {
  ...
  val view: EditText = ...findViewById(editTextId)
  if (view.isUsingTextFilter() && view.isUsingDigitsFilter()
    || view.maxLength < text.length ) {
    combinedMatcher.performAction(typeText(text))
  } else {
    combinedMatcher.performAction(replaceText(text))
  }
}
```

**2. Maybe add a parameter to a second version of `writeTo()` to use `typeText()` instead of `replaceText()`.**

Example pseudo code:

```java
fun writeTo(@IdRes editTextId: Int, text: String, useTypeText: Boolean) {
  ...
  if (useTypeText) {
    combinedMatcher.performAction(typeText(text))
  } else {
    combinedMatcher.performAction(replaceText(text))
  }
}
```

**Comment by Sloy** [comment]
How about we add another function that uses `typeText` instead of `replaceText`?
I can't think of a good name though. `writeLetterByLetter`? 😕

**Comment by EsteveAguilera** [comment]
What about `typeTo`? 🤷‍♂️

**Comment by Sloy** [comment]
Genius!

**Comment by alorma** [comment]
It looks that `typeText` doesn't breaks any test... #396

**Comment by ozmium** [comment]
I like the idea of `typeTo()`. And perhaps add some documentation like:

```java
/**
 * This uses [Espresso.replaceText()] which will remove any existing text
 * and insert the characters directly, disregarding any EditText properties
 * like `'maxLength`, `textFilter`, etc.
 */
fun writeTo(@IdRes editTextId: Int, text: String) {
  ...
}

/**
 * This uses [Espresso.typeText()] which will tap once on the EditText
 * and type the characters like an on-screen keyboard. Most EditText
 * properties like `'maxLength`, `textFilter`, will be honored.
 */
fun typeTo(@IdRes editTextId: Int, text: String) {
  ...
}
```

**Comment by alorma** [comment]
cool @ozmium .

Can you open a PR with that and do some tests? I'm sure it will be a great addition to Barista

**Comment by ozmium** [comment]
I think I can start an initial Pull Request, but I will probably not be able to write a comprehensive set of unit tests or UI tests for it. Perhaps someone can help with that.

**Comment by alorma** [comment]
Sure, @rocboronat here is the expert on writing (and asking for) test XD

We will discuss and help as much as we can!

**Comment by rocboronat** [comment]
#397 fixes this issue
