### ISSUE TITLE
Proposal: Semantic pull requests

### ISSUE THREAD

**Issue by alorma** [AdevintaSpain/Barista#421]
**Description what you'd like to happen:**

I've know that exist some actions for github actions to help improving pull requests.

I've used this one: https://github.com/marketplace/actions/semantic-pull-request#:~:text=v2.1.1-,action%2Dsemantic%2Dpull%2Drequest,title%20as%20the%20commit%20message.
based on: https://www.conventionalcommits.org/en/v1.0.0/

This will make that all PRs have a title like:

```
fix: Error on assertDisplayed()
feat: Add assertTextInputText()
```

etc...

**Comment by alorma** [comment]
https://github.com/commitizen/conventional-commit-types/blob/master/index.json

List of all default tags allowed, it can be changed

**Comment by rocboronat** [comment]
IMHO, it fixes a problem we don't have... but I have to say I never tried an approach like that, so...

**Comment by alorma** [comment]
Just a way to make sure the PR has some semantic, easier to read the merge commits and understand what the commit / PR was about, new feature? a bug fix? ...

**Comment by Sloy** [comment]
We don't have that many PRs, I think. 
I'm with @rocboronat, I don't see it solves a problem we have.

However, it would add more CI code to maintain and more restrictions on PRs.
