### ISSUE TITLE
Download instruction in README.md does now work anymore

### ISSUE THREAD

**Issue by kenobasedow** [AdevintaSpain/Barista#425]
**Library Version:**

3.9.0
  
**Describe the Bug:**

When using dependency in app gradle file like described in README.md than barista library cannot be found:
```
Failed to resolve: com.adevinta.android:barista:3.9.0
Show in Project Structure dialog
Affected Modules: app
```
**Steps to reproduce the bug:**
1. Add dependency to app gradle file:
```
androidTestImplementation('com.schibsted.spain:barista:3.9.0') {
        exclude group: 'org.jetbrains.kotlin' // Only if you already use Kotlin in your project
}

```
2. Top level gradle file contains:
```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
```
3. Press "Sync now"

`com.schibsted.spain:barista` is also not working.

**Expected Behavior:**

The library should be contained in one of the maven repositories.

**Comment by Sloy** [comment]
Hi @kenobasedow! Thanks for reporting it.
Right now Barista is hosted on JCenter. I guess the instructions never specified it because it was pretty standard. But since their announcement of shutting JCenter down, it's not so standard anymore. We should be more specific in the readme!

Temporary fix: 
```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}
```

But we're in the process to migrate to Maven Central, so this won't be needed once we migrate. Related: https://github.com/AdevintaSpain/Barista/issues/382

**Comment by kenobasedow** [comment]
Hello @Sloy,
i see.
But on jcenter() it is still
`com.schibsted.spain:barista:3.9.0`
instead of
`com.adevinta.android:barista:3.9.0`
Maybe you add a note to your README.md that you need to get it with `schibsted` from `jcenter()` so that the people are not confused.
Regards Keno

**Comment by Sloy** [comment]
Aaah you're totally right! We changed the dependency coordinate in the Readme but it's not ready yet! Sorry 🙏 

Yes, we should add some sort of notice. Thanks for reporting it!

**Comment by Sloy** [comment]
I updated the readme in https://github.com/AdevintaSpain/Barista/pull/426
I hope the new explanation is good enough now 😃 
Thanks Keno!

**Comment by kenobasedow** [comment]
Yes that change would be fine.
When will it be visible on the start page?
https://github.com/AdevintaSpain/Barista
Is it still on a branch?

**Comment by Sloy** [comment]
Yes, it was on the PR only. 
But it's visible now :)
