### ISSUE TITLE
How to check font family 

### ISSUE THREAD

**Issue by karan7717** [AdevintaSpain/Barista#427]
I want to check text font family , is there any way , thanks

**Comment by alorma** [comment]
Hi @karan7717 

Do you know it TextView (or children) have any method to get the current font family?

If there's the case, could you open a PR for it? Maybe checking the `assertTextColorIs` method

**Comment by alorma** [comment]
Hi @karan7717 We are going to close this issue. If you need help integrating it, or come up with a solution, feel free to reopen the issue or open a pull requests.
