### ISSUE TITLE
Hello, Barista is not able to click  IN-APP Billing Library

### ISSUE THREAD

**Issue by faltutechy** [AdevintaSpain/Barista#429]
*Ver3.9.0

**Describe the Bug:**

A clear description of what is the bug is.

**Steps to reproduce the bug:**
1. Try to Launch IN APP Billing Library Popup.
2. Try to subscribe.
3. Not able to perform click on Subscribe button.

**Expected Behavior:**

It should be able to click on Subscribe button and perform purchase.
<img width="328" alt="Screenshot 2021-07-19 at 11 08 01 AM" src="https://user-images.githubusercontent.com/69748785/126097017-bbd7d76a-1a3f-4011-8ea2-ec7a68c5546b.png">

**Comment by Sloy** [comment]
Hello @faltutechy!
The In-App dialog is part of an external application, not your own app. Barista, like Espresso, can't interact with views outside of your app. 
To do that, you need to use [UI Automator](https://developer.android.com/training/testing/ui-automator) instead. You can see a similar example in our [PermissionGranter](https://github.com/AdevintaSpain/Barista/blob/master/library/src/main/java/com/adevinta/android/barista/interaction/PermissionGranter.kt) class, which interacts with the system's permission dialog.

Good luck!
