### ISSUE TITLE
Upgrade to latest Espresso version

### ISSUE THREAD

**Issue by VictorIreri** [AdevintaSpain/Barista#430]
This brilliant library is [using Espresso 3.1.1](https://github.com/AdevintaSpain/Barista/blob/master/library/build.gradle.kts) which was released in 2018. I think it's about time it was updated to a later version, ideally the latest **3.4.0** https://github.com/android/android-test/releases/tag/androidx-test-1.4.0

**Comment by Sloy** [comment]
Totally right! I can't do this right now, but a Pull Request would be welcomed :)

**Comment by lordcodes** [comment]
I believe this can be closed, as the PR was merged.

**Comment by Sloy** [comment]
@lordcodes yep, thanks for the head's up :)

**Comment by VictorIreri** [comment]
Thanks @JJaviMS!
