### ISSUE TITLE
[Discussion] Why assertNotDisplayed does not fail 

### ISSUE THREAD

**Issue by moutyque** [AdevintaSpain/Barista#464]
Hello,
I came across this awesome lib and using it in my test to ease my coding process.
I encountered a situation I am not sure to understand.
I wanted to assert that a textView is not displayed the "Legume" in the screen shot:
![image](https://user-images.githubusercontent.com/25465217/201729974-d765e795-5250-4ae8-b9a7-d93289e7d921.png)
So I expected: assertNotDisplayed("Legume") to fail but it is not the case.
However assertNotExist("Legume") do fail (which is good).

Question is: why assertNotDisplayed do not fail ? How to use it properly ?
I read the README but did not find anything useful for my question.

Thank in advance fore any clarification.

**Comment by Sloy** [comment]
I think this could be a bug. By looking at the implementation of assertNotDisplayed:
```
withCompatText(text).assertAny(not(isDisplayed()))
```
There's a flaw in the logic. Instead of "assert any not displayed" , it should be "assert none is displayed".

@moutyque in your case, maybe you have another instance of a TextView with "Legume" not currently displayed in your view hierarchy?

**Comment by moutyque** [comment]
Hello,
Thx for your answer I was afraid the project was dead.
You are right, I am using Tabs and in another tab the "Legume" text is displayed.
I found a workaround with:
fun assertDepDoesNotExist(depName: String){
        onView(
            allOf(
                withId(R.id.tv_dep_name), <= Id of the view holding the text, could be pass as a param
                withText(depName), <= Text I am checking
                withParent(
                    allOf(
                        withParent(withId(R.id.ll_complet_line)) <= Some ancestor id
                    )
                ),
                isDisplayed()
            )
        ).check(ViewAssertions.doesNotExist())
