### ISSUE TITLE
Documentation uses octal number

### ISSUE THREAD

**Issue by ajburley** [AdevintaSpain/Barista#504]
> `setDateOnPicker(1986, 03, 23);`

The README uses an octal number (`03` in Java), probably unintentionally, as part of a date representation. If this was changed to `09` for example, the code would fail to compile. It only works because octal numbers are the same as decimal numbers for 0-7.

Should be changed to `setDateOnPicker(1986, 3, 23);`.

**Comment by rocboronat** [comment]
Thanks a lot, @ajburley! It's been exactly as you described. 100% unintentional 😅 My fault ✋
